### ISSUE TITLE
Deepwalk on directed graphs

### ISSUE THREAD

**Issue by tsuresh83** [phanein/deepwalk#25]
What am I missing? Embeddings produced with `deepwalk --format edgelist --undirected false --input file --out embedfile` are identical to `deepwalk --format edgelist --input file --out embedfile`. The question is how do I create embeddings for directed graphs? Please help.

**Comment by GTmac** [comment]
For posterity: you are right, the current implementation of DeepWalk does not support directed graphs.   To run DeepWalk on directed graphs, you need to:
* Generate directed random walks (this is straightforward);
* Hack the underlying gensim word2vec module, so that it only considers the words to the **left** of the current word (node). This part could be a little bit tricky.
