### ISSUE TITLE
A Question about train set

### ISSUE THREAD

**Issue by BenchengY** [phanein/deepwalk#41]
I would like to know Do you use a part of data(labeled nodes) or all the data in the embedding process(not the classification)? 
as i don't know this sentence 'Specically, we randomly sample a portion (TR) of the labeled nodes, and use them as training data.' in your paper mean. 
You use all the data for embedding and then use part of nodes for classification train set?
thanks !

**Comment by GTmac** [comment]
Yess, we generate DeepWalk embedding for all nodes as features and sample a part of nodes along with their labels as training data.

**Comment by BenchengY** [comment]
OK, thanks GTmac. 
Then I have another question, Why not use a part of nodes to train the DeepWalk model , after training, then run the trained model to get the embedding vector of all nodes ?
As  we usually use a part of data as training data to train the deep model , and a part of data as validation  data and test data.
if use all of the nodes to train the DeepWalk, then It seems do not consider about generalization ability ?
Thanks!

**Comment by GTmac** [comment]
Because DeepWalk is an unsupervised model -- it takes the network structure as input and outputs node embeddings for all nodes in the network.

In that sense, the classification task is a downstream task for evaluation purpose only. If we have labels associated with nodes, we could build a LR classifier which takes DeepWalk embeddings as features and predicts node labels.

**Comment by BenchengY** [comment]
Oh, I know . you means we usually use all of the data to train the model rather than a part of data in unsupervised learning. right?
Thanks!

**Comment by GTmac** [comment]
Yes, you are right :)
