### ISSUE TITLE
Is the code just only applicable to undirected and unweighted graphs?

### ISSUE THREAD

**Issue by Ashinhuang** [phanein/deepwalk#52]
Dear sir,
the code is just only  applicable to undirected and unweighted graphs, yes?
for weighted and directed graphs,it does not work, really?

**Comment by GTmac** [comment]
Yes, this version only works for undirected and unweighted graphs. However, it is not very hard to extend DeepWalk to directed and weighted graphs:

* Please refer to #26 for an extension on weighted graphs.
* For directed graphs, you might need to hack the underlying gensim word2vec module: instead of using both the neighbors on the left and right side of the chosen node (in a random walk sequence), you need to use only the neighbors on the left.

**Comment by Ashinhuang** [comment]
Thanks a lot
